language: node_js
node_js:
  - 6
  - 7
  - 8
  - 9
os:
  - linux
  - centos
  - macosx
  - windows
before_script:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.0.4.tgz -O /tmp/mongodb.tgz
  - tar -xvf /tmp/mongodb.tgz
  - mkdir /tmp/data
  - ${PWD}/mongodb-linux-x86_64-3.0.4/bin/mongod --dbpath /tmp/data  &
  - until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done
  - sleep 3
script:
  - npm test
